### ISSUE TITLE
Unable to run the test

### ISSUE THREAD

**Issue by ugobriasco** [chrisluis/su-hw-challenge-answer-chrisluis#1]
By following the readme, the command  `docker run --network=host su-hw-challenge-chrisluis bash -c "./run_test.sh"` returns an authentication error.

Following the details:

![Screenshot 2019-08-19 at 15 33 33](https://user-images.githubusercontent.com/9917415/63269569-c2c3b700-c296-11e9-9e13-bd8a97a865b1.png)

**Comment by chrisluis** [comment]
Hello,

The command should be ```docker run --network=host chrisluis/su-hw-challenge-chrisluis bash -c "./run_test.sh"```

Amended the instruction.

**Comment by ugobriasco** [comment]
Thank you!
