### ISSUE TITLE
Unable to generate reports

### ISSUE THREAD

**Issue by ugobriasco** [chrisluis/su-hw-challenge-answer-chrisluis#2]
From the readme:
```
After running the script successfully. It will generate a comprehensive test report. However container don't save the generated test result. You can view a sample of test result by cloning this repository then go to Results folder. Open log.html using your browser.
```
Unfortunately, a sample of the test results would not help a developer to continuously improve the application (e.g. after fixing the issues found), therefore the application should somehow present test results to the user.

**Comment by chrisluis** [comment]
Hello yes, it will generate a real-time report once run locally (outside container). Volume from the container needs to be mounted on the host. I was thinking when I created the container, the purpose of the docker was to isolate external files from the host machine for security purposes. Though, it can be done :)

Real-report will be generated for every run of the automation scripts. Not only a sample file :)

**Comment by chrisluis** [comment]
Hello,

In any case, you may do this to get the generated test results from the run automation script.

1. Create a folder where you want the generated test result to be saved.
2. Go to that folder using the Terminal
3. Run the command below line by line.
```
docker run -it chrisluis/su-hw-challenge-chrisluis
mkdir Results
exit
docker run --network=host -it -v $(pwd):/Results chrisluis/su-hw-challenge-chrisluis
./run_test.sh
```
This will mount your folder to the container and will run the test from shell script.

4. Open the folder you recently created on your host machine. You will see 3 files generated. These are the test results generated from the automation script.
5. Open the log.html using your browser.

High level test result is report.html
In depth test result is log.html

Let me know if you encountered any problem. I hope this answers the question.

**Comment by ugobriasco** [comment]
Yes, that's the way!
